# Generated by Django 3.1.4 on 2021-01-04 12:58

from django.db import migrations, models
import proje_blockchain.node1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=2)),
                ('p_hash', models.CharField(default=proje_blockchain.node1.models._pcreateHash, max_length=64, unique=True)),
                ('hash', models.CharField(default=None, max_length=64, null=True, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
